version: "2.1"
services:
  platform_c:
      container_name: platform_c
      image: ${DEPLOY_IMAGE}
      volumes:
        - ${SHARED_VOLUME_PATH}/:/home/trainee/work/
      stdin_open: true
      privileged: true
      cap_add:
        - ALL
      tty: true
      cpus: 2.0
      mem_limit: '2000000000'
      memswap_limit: '2000000000'
      mem_swappiness: 0
      command:
        /bin/bash


